# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87fa18317023ddb25f42df0c45d15fd23dfc2a59f4f689ce278408692fa395029a9bed6716fb0aa792586da6b288691efe19b99980ebad9904ba7b4f4d4a36ec

test:
  secret_key_base: 1c8de4475058fc7eae250c68d92398604364088a1998547aa6d09e5e6cf88f951ce12c0540b3c400c14c9073267a630c1b7747b6876f08671c8063cb1f92b94b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
